version: "3"

services:
    postgres:
        image: postgres:12.3-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
        ports:
            - 5432:5432
        volumes:
            - /home/${DEFAULT_USER}/data-disk/pgdata:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4:4.23
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
            PGADMIN_LISTEN_PORT: 80
        ports:
            - 80:80
        volumes:
            - /home/${DEFAULT_USER}/data-disk/pgadmin:/var/lib/pgadmin
        depends_on:
            - postgres
        
x-yc-disks:
  - device_name: pgdata
    fs_type: ext4
    host_path: /home/${DEFAULT_USER}/data-disk